spring:
  profiles:
    active: @profileActive@
ding_corpid: dingzw47c9opljqayjdc
ding_corpsecret: 1cnY4oIRM0VydnO3YHb8wNa2CDL70jxxlbUfush-iVWTT1bU1njaEpqdM1hdSNMV
---
server:
  port: 8090
  servlet:
    context-path: /ftdp-web
spring:
  profiles: dev
  application:
    name: ftdp-provider
#    TODO 数据库链接地址 账户 密码
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/ftdp_dev?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 50
      validation-query: SELECT 1
      test-while-idle: true
      aop-patterns: com.tfjybj.physical.*
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid
  #redis  TODO 修改地址 端口
#  redis:
#    host: 192.168.22.60
#    port: 6379
#    password:
#    database: 0
#    timeout: 300000ms
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 500
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    mapUnderscoreToCamelCase: true
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: ID_WORKER_STR

#分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#
#  # fastdfs3
#fdfs:
#  groupName: group2
#  so-timeout: 1500
#  connect-timeout: 600
#  tracker-list: 192.168.22.133:22122
#  replace-ip:
#    source: 192.168.22.133
#    dest: 192.168.22.133;
#  realIp: 192.168.22.133
  #pool:
  #jmx-enabled:false
#logging:
#  level:
#    ROOT: WARN,DEBUG,ERROR,INFO
#  file:
#    name: mylog.log
---
  server:
    port: 8090
    servlet:
      context-path: /ftdp-web
  spring:
    profiles: prod
    application:
      name: ftdp-provider
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://192.168.22.58:3306/english?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: english
      password: english
      druid:
        initial-size: 2
        min-idle: 2
        max-active: 50
        validation-query: SELECT 1
        test-while-idle: true
        aop-patterns: com.tfjybj.physical.*
        stat-view-servlet:
          url-pattern: /druid/*
          reset-enable: true
          login-username: druid
          login-password: druid
    #redis  TODO 修改地址 端口
    redis:
      host: 192.168.22.60
      port: 6379
      password:
      database: 0
      timeout: 300000ms
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 500
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    global-config:
      mapUnderscoreToCamelCase: true
      db-config:
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
        id-type: ID_WORKER_STR

  #分页
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    #
    #  # fastdfs3
    #fdfs:
    #  groupName: group2
    #  so-timeout: 1500
    #  connect-timeout: 600
    #  tracker-list: 192.168.22.133:22122
    #  replace-ip:
    #    source: 192.168.22.133
    #    dest: 192.168.22.133;
    #  realIp: 192.168.22.133
    #pool:
    #jmx-enabled:false
#  logging:
#    level:
#      ROOT: WARN,DEBUG,ERROR,INFO
#    file:
#      name: mylog.log

---
server:
  port: 8090
  servlet:
    context-path: /ftdp-web
spring:
  profiles: test
  application:
    name: ftdp-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.22.58:3306/english?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: english
    password: english
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 50
      validation-query: SELECT 1
      test-while-idle: true
      aop-patterns: com.tfjybj.physical.*
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid
  #redis  TODO 修改地址 端口
  redis:
    host: 192.168.22.60
    port: 6379
    password:
    database: 0
    timeout: 300000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    mapUnderscoreToCamelCase: true
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: ID_WORKER_STR

#分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  #
  #  # fastdfs3
  #fdfs:
  #  groupName: group2
  #  so-timeout: 1500
  #  connect-timeout: 600
  #  tracker-list: 192.168.22.133:22122
  #  replace-ip:
  #    source: 192.168.22.133
  #    dest: 192.168.22.133;
  #  realIp: 192.168.22.133
  #pool:
  #jmx-enabled:false
#logging:
#  level:
#    ROOT: WARN,DEBUG,ERROR,INFO
#  file:
#    name: mylog.log
